# -*- coding: utf-8 -*-
"""GE_Baseline_Torch_Model_v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
"""

!nvidia-smi

from google.colab import drive
drive.mount('/content/drive')

# Setup conda environment to download RDKIt
!wget -c https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
!chmod +x Miniconda3-4.5.4-Linux-x86_64.sh
!bash ./Miniconda3-4.5.4-Linux-x86_64.sh -b -f -p /usr/local

# update 1
!conda install -q -y --prefix /usr/local python=3.6 ujson

# update 2
import sys
sys.path.append('/usr/local/lib/python3.6/site-packages')
# test it
import ujson
print(ujson.dumps({1:2}))

#RDKIT installation
!conda install -y -c rdkit rdkit

# Pytorch geometric
# Install required packages.
!pip install -q torch-scatter==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
!pip install -q torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
!pip install -q git+https://github.com/rusty1s/pytorch_geometric.git

# Reverting back to previous version of torch 
# !pip install torch==1.0.0 torchvision==0.2.1
# !conda install -c rdkit rdkit
